name: Provision and Deploy to GKE


on:
  push:
    branches:
      - GKEWebappDUMMYYYYYYYY

# jobs:
#   build:
#     runs-on: self-hosted

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      
      - name: Write GCP credentials to file
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
      
      - name: Authenticate with GCP
        run: |
          # echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file="${{ github.workspace }}/gcp-key.json"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend Docker Image to Docker Hub
        run: ./build_and_push_docker_cr.sh frontend
        working-directory: ./Application

      - name: Build and Push Backend Docker Image to Docker Hub
        run: ./build_and_push_docker_cr.sh backend
        working-directory: ./Application

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v1

      # - name: Terraform Init
      #   run: terraform init
      #   working-directory: ./GKE
      
      # - name: Terraform Format
      #   run: terraform fmt -recursive
      #   working-directory: ./GKE

      # - name: Terraform Validate
      #   run: terraform validate
      #   working-directory: ./GKE

      # - name: Terraform Plan
      #   env:
      #     TF_VAR_gcp_credentials_file: "${{ github.workspace }}/gcp-key.json"
      #     TF_VAR_project_id: "${{ secrets.GCP_PROJECT_ID }}"
      #   run: terraform plan
      #   working-directory: ./GKE
        
      # - name: Terraform Apply
      #   env:
      #     TF_VAR_gcp_credentials_file: "${{ github.workspace }}/gcp-key.json"
      #     TF_VAR_project_id: "${{ secrets.GCP_PROJECT_ID }}"
      #   run: terraform apply -auto-approve
      #   working-directory: ./GKE

      - name: Configure kubectl
        run: gcloud container clusters get-credentials upendra-kumar-440007-gke --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Deploy to GKE
        run: |
          kubectl apply -f ./k8s-gcp/
        working-directory: ./Application/
